spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
one-fit:
  otp:
    retry-wait-time: 5 # in seconds
    retry-count: 3
    time-to-live: 60 # in seconds

  notification:
    sms:
      eskiz: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDgwOTIyNzMsImlhdCI6MTcwNTUwMDI3Mywicm9sZSI6InRlc3QiLCJzdWIiOiI1NTQ0In0.UaOOvcYf0TBtIzy5kBm2YOZ2jqM-jiWRP3g9Q1rjrsc

  security:
    token:
      expiration: 86400
      secret: hDqp3P1lsCHRegptkGeoXbH0Hz7ar1wJ0E1erPBPjTSGMWw9cCwzCf43ZhBNZ01E


