spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

one-fit:
  otp:
    retry-wait-time: 60 # in seconds
    retry-count: 3
    time-to-live: 300 # in seconds
  notification:
    sms:
      eskiz: FMrOwoLPY38lu29ODuC4wIHvUX0yFmM3p8qNla9r
  security:
    token:
      expiration: 86400
      secret: FMrOwoLPY38lu29ODuC4wIHvUX0yFmM3p8qNla9r

